- name: Install the package "nginx"
  apt: 
    name: nginx
    update_cache: yes

- name: Copy index.html to the server
  ansible.builtin.copy:
    src: ../files/default 
    dest: /var/www/html

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
