- name: Copy influxdb-exporter binary
  ansible.builtin.copy:
    src: influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/prometheus-influxdb-stats-exporter
    owner: prometheus
    mode: u+x

- name: Copy prometheus-influxdb-exporter
  ansible.builtin.copy:
    src: prometheus-influxdb-stats-exporter.service
    dest: /etc/systemd/system/
  notify: Reload daemons

- name: Service prometheus-influxdb-exporter 
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter.service
    state: started
    enabled: yes
