- name: Service rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes

- name: Copy 10-telegraf.conf
  ansible.builtin.copy:
    src: 10-telegraf.conf
    dest: /etc/rsyslog.d/
  notify: Restart rsyslog
