- name: Grafana directory
  ansible.builtin.file:
    name: /opt/grafana
    state: directory

- name: Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: yes

- name: Grafana docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: grafana
    image: grafana/grafana
    published_ports: "3001:3000"
    volumes: /opt/grafana:/etc/grafana
