- name: Grafana directory
  ansible.builtin.file:
    name: /opt/grafana
    state: directory

- name: Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini

- name: Grafana dashboard and datasource
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: "/opt/grafana/provisioning/{{ item }}"
  loop:
    - dashboards
    - datasources

- name: Grafana dashboards
  ansible.builtin.copy:
    src: ../files/datasource.yaml
    dest: /opt/grafana/provisioning/datasources/default.yaml

- name: Grafana dashboards
  ansible.builtin.copy:
    src: ../files/dashboard.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml

- name: main.json
  ansible.builtin.copy:
    src: ../files/main.json
    dest: /opt/grafana/provisioning/dashboards/main.json 

- name: mysql.json
  ansible.builtin.copy:
    src: ../files/mysql.json
    dest: /opt/grafana/provisioning/dashboards/mysql.json 

- name: syslog.json
  ansible.builtin.copy:
    src: ../files/syslog.json
    dest: /opt/grafana/provisioning/dashboards/syslog.json 

- name: Grafana docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
