- name: Install uWSGI package uwsgi
  apt:
    name: uwsgi
    update_cache: yes

- name: Install uWSGI package uwsgi-plugin-python3
  apt: 
    name: uwsgi-plugin-python3
    update-cache: yes

- name: Copy agama.ini to desired directory
  ansible.builtin.copy:
    src: ../files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI

- name: uWSGI service                                                           
  ansible.builtin.service:                                                      
    name: uwsgi                                                                 
    state: started                                                              
    enabled: yes         
