- name: Install uWSGI package uwsgi
  apt:
    name: uwsgi

- name: Install uWSGI package uwsgi-plugin-python3
  apt: 
    name: uwsgi-plugin-python3

- name: Copy agama.ini to desired directory
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
  no_log: true
  notify: Restart uWSGI

- name: uWSGI service                                                           
  ansible.builtin.service:                                                      
    name: uwsgi                                                                 
    state: started                                                              
    enabled: yes         
