---
- name: Collect info about all VMs 
  hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - setup:

- name: Init
  hosts: all 
  become: yes
  gather_facts: no 
  roles: 
    - init
    - backup
  tags:
    - i

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles: 
    - bind
    - bind_exporter
  tags:
    - b

- name: Systemd-resolved
  hosts: all
  become: yes
  gather_facts: no
  roles: 
    - systemd-resolved

- name: Node exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - node_exporter

- name: Database server
  hosts: mysql_servers
  become: yes
  gather_facts: no 
  roles:
    - mysql
    - mysql_exporter
    - mysql_backup
  tags:
    - m

- name: NGINX
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - nginx
    - nginx_exporter
  tags:
    - n

- name: Haproxy and Keepalive
  hosts: haproxy
  become: yes
  gather_facts: no
  roles: 
    - haproxy
    - haproxy_exporter
    - keepalived
    - keepalived_exporter
  tags:
    - hk

- name: Docker bug
  hosts: agama_app
  become: yes
  gather_facts: no
  roles:
    - iptables
  tags:
    - i

- name: Docker
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - docker
  tags: 
    - d

- name: Agama
  hosts: agama_app
  become: yes
  gather_facts: no
  roles: 
    - agama
  tags:
    - a

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  gather_facts: no
  roles: 
    - prometheus
  tags:
    - p

- name: Grafana
  hosts: grafana_servers
  become: yes
  gather_facts: no
  roles: 
    - grafana
  tags: 
    - g

- name: InfluxDB
  hosts: influxdb_servers
  become: yes
  gather_facts: no
  roles:
    - influxdb
    - influxdb_exporter
    - influxdb_backup
  tags:
    - x

- name: Pinger
  hosts: pingers
  become: yes
  gather_facts: no
  roles:
    - pinger

- name: Rsyslog
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags: 
    - r
