---
- name: Collect info about all VMs 
  hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - setup:

- name: Init
  hosts: all 
  become: yes
  gather_facts: no 
  roles: 
    - init

- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: no 
  roles:
    - mysql
    - mysql_exporter

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles: 
    - bind
    - bind_exporter

- name: Agama
  hosts: agama_app
  become: yes
  gather_facts: no
  roles: 
    - agama
    - uwsgi

- name: NGINX
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - nginx
    - nginx_exporter
  tags:
    - n

- name: Node exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - node_exporter

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  gather_facts: no
  roles: 
    - prometheus

- name: Grafana
  hosts: grafana_servers
  become: yes
  gather_facts: no
  roles: 
    - grafana
  tags: 
    - g

- name: InfluxDB
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - influxdb
  tags:
    - x

- name: Pinger
  hosts: pingers
  become: yes
  gather_facts: no
  roles:
    - pinger
  tags: 
    - p

- name: Systemd-resolved
  hosts: all
  become: yes
  gather_facts: no
  roles: 
    - systemd-resolved
