---
- name: Collect info about all VMs 
  hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - setup:

- name: Init
  hosts: all 
  become: yes
  gather_facts: no 
  roles: 
    - init

- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: no 
  roles:
    - mysql

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles: 
    - bind

- name: Web server
  hosts: web_servers
  become: yes
  gather_facts: no
  roles: 
    - agama
    - uwsgi

- name: NGINX
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - nginx

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  gather_facts: no
  roles: 
    - prometheus

- name: Node exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - node_exporter

- name: Systemd-resolved
  hosts: all
  become: yes
  gather_facts: no
  roles: 
    - systemd-resolved
