- name: /opt/agama
  ansible.builtin.file:
    state: directory
    path: /opt/agama

- name: Download dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Agama image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Agama containers
  community.docker.docker_container:                                            
    container_default_behavior: no_defaults                                     
    name: "{{ item.key }}"
    image: agama
    published_ports: "{{ item.value }}:8000" 
    env: AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  loop: "{{ agama_ports | dict2items }}"
