- name: Add the user backup and generate ssh keys
  ansible.builtin.user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Create directory restore for user backup                                
  ansible.builtin.file:                                                            
    path: /home/backup/restore
    state: directory                                                            
    mode: '0644'

- name: Install duplicity
  apt:
    name: duplicity

- name: Copy known_hosts
  ansible.builtin.template:
    src: ../templates/known_hosts
    dest: /home/backup/.ssh/
    mode: '0644'
