- name: Create a directory for user backup                                
  ansible.builtin.file:                                                            
    path: /home/backup/influxdb
    state: directory                                                            
    owner: backup
    mode: '0644'
