- name: Install package "mysql"
  apt:
    name: mysql-server

- name: Install package "python3-pymysql"
  apt:
    name: python3-pymysql

- name: MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Replication user
  community.mysql.mysql_user:
    name: "{{ replication_user }}"
    password: "{{ replication_mysql_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: copy override.cnf to /etc/mysql/mysql.conf.d/
  ansible.builtin.template:
    src: ../files/override.cnf
    dest: /etc/mysql/mysql.conf.d/
  notify: Restart MySQL

- name: MySQL replica RO mode on
  community.mysql.mysql_variables:
    variable: read_only
    value: 'ON' 
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: inventory_hostname !=  mysql_host 
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: MySQL primary R0 mode off
  community.mysql.mysql_variables:
    variable: read_only
    value: 'OFF' 
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: inventory_hostname ==  mysql_host 
  notify:
    - Reset MySQL source
    - Reset MySQL replica
