- name: Install package "mysql"
  apt:
    name: mysql-server

- name: MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: copy override.cnf to /etc/mysql/mysql.conf.d/
  ansible.builtin.copy:
    src: ../files/override.cnf
    dest: /etc/mysql/mysql.conf.d/
  notify: Restart MySQL
