- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart mysql-exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: yes
