- name: Add the user roman to managed hosts
  ansible.builtin.user:
    name: roman

- name: Set authorized keys for roman from url
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys

- name: Add the user juri to managed hosts
  ansible.builtin.user: 
    name: juri 

- name: Set authorized keys for juri from url
  ansible.posix.authorized_key: 
    user: juri 
    state: present
    key: https://github.com/hudolejev.keys
