- name: Install fping
  apt:
    name: fping

- name: Create user pinger
  ansible.builtin.user:
    name: pinger

- name: Copy pinger.conf
  ansible.builtin.copy:
    src: pinger.conf
    dest: /etc/pinger/
  notify: Restart pinger

- name: Copy pinger.sh
  ansible.builtin.copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    owner: pinger
    mode: u+x

- name: Copy pinger.service
  ansible.builtin.copy:
    src: pinger.service
    dest: /etc/systemd/system/
  notify: 
    - Reload daemons
    - Restart pinger

- name: Pinger service
  ansible.builtin.service:
    name: pinger
    state: started
    enabled: yes
