- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived

- name: keepalived script
  ansible.builtin.template:
    src: ha88.j2
    dest: /usr/local/bin/ha88
    mode: '755'

- name: keepalived.conf
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Service keepalived
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - haproxy
    - keepalived
