- name: Install haproxy exporter
  ansible.builtin.apt: 
    name: prometheus-haproxy-exporter

- name: haproxy exporter config
  ansible.builtin.template:
    src: templates/prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy-exporter
  
- name: Service prometheus-haproxy-exporter
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
