- name: Install Prometheus
  apt:
    name: prometheus

- name: Service prometheus                                                            
  ansible.builtin.service:                                                      
    name: prometheus                                                                 
    state: started                                                              
    enabled: yes                                                                
                   
- name: prometheus.yaml
  ansible.builtin.template:
    src: ../templates/prometheus.yml
    dest: /etc/prometheus/
  notify: Restart prometheus

- name: /etc/default/prometheus
  ansible.builtin.template:
    src: ../templates/prometheus
    dest: /etc/default/
  notify: Restart prometheus
