- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Grafana password
  shell:
    cmd: grafana-cli admin reset-admin-password {{ grafana_password }}
