- name: Docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Log into DockerHub
  community.docker.docker_login:
    username: manmanmano
    password: "{{ docker_password }}"

- name: Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
