- name: Install package "bind9"
  apt:
    name: bind9

- name: Service bind
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Copy new named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: true
  notify: Restart bind

- name: Copy new named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind

- name: Copy db.startup_name
  when: inventory_hostname in groups['dns_master']
  ansible.builtin.template:
    src: db.clounsible.mano.j2
    dest: /var/cache/bind/db.{{startup_name}}
    force: no
  notify: Reload bind
