- name: Install package "bind9"
  apt:
    name: bind9

- name: Service bind
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Copy new named.conf.options
  ansible.builtin.template:
    src: ../templates/named.conf.options
    dest: /etc/bind/
  notify: Restart bind

- name: Copy db.startup_name
  ansible.builtin.template:
    src: ../templates/db.clounsible
    dest: /etc/bind/
  notify: Restart bind
