- name: Install package "bind9"
  apt:
    name: 
      - bind9
      - python3-dnspython

- name: Service bind
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Copy db.startup_name
  when: inventory_hostname in groups['dns_master']
  ansible.builtin.template:
    src: db.clounsible.mano.j2
    dest: /var/cache/bind/db.{{startup_name}}
    force: no
  notify: Reload bind

- name: Copy db.reverse
  when: inventory_hostname in groups['dns_master']
  ansible.builtin.template:
    src: db.reverse.j2
    dest: /var/cache/bind/db.reverse
    force: no
  notify: Reload bind

- name: Copy new named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: true
  notify: Restart bind

- name: Copy new named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind

- name: Force notified handlers to restart at this point
  meta: flush_handlers 

- name: Nsupdate A records
  when: inventory_hostname in groups['dns_master']
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key }}"
    server: "localhost"
    zone: "{{ startup_name }}"
    type: "A"
    record: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ dns_a_records | dict2items }}"
  notify: Restart bind

- name: Nsupdate CNAME records
  when: inventory_hostname in groups['dns_master']
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key }}"
    server: "localhost"
    zone: "{{ startup_name }}"
    type: "CNAME"
    record: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items }}"
  notify: Restart bind
